version: '3'
services:
  stress-tester:
    build: .
    depends_on:
      - "sphinx"
    command: [ "./wait-for", "sphinx:9306", "-t", "1000", "--", "php", "./test.php", "--data=test.txt", "--plugin=rt_insert_sphinx.php", "-c=10", "-b=10", "--limit=10000" ]
    container_name: "stress-tester"
  sphinx:
    build: 
      context: .
      dockerfile: Dockerfile_sphinx
    ports:
      - "9306:9306"
    container_name: "sphinx"